DROP DATABASE SWEETNEWS;

CREATE DATABASE SWEETNEWS;

SET SCHEMA SWEETNEWS;

CREATE TABLE SOURCES (
	ID VARCHAR(3) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(50),
	URL VARCHAR(50) NOT NULL,
	CATEGORY VARCHAR(10) NOT NULL,
	LANGUAGE VARCHAR(3) NOT NULL WITH DEFAULT 'ENG',
	COUNTRY VARCHAR(3) NOT NULL WITH DEFAULT 'USA',
	URL_LOGO VARCHAR(100) NOT NULL,
	
	CONSTRAINT Source_PK PRIMARY KEY(ID)
);
