-- MySQL Script generated by MySQL Workbench
-- 04/22/17 14:07:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sweetnews
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sweetnews
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sweetnews` DEFAULT CHARACTER SET utf8 ;
USE `sweetnews` ;

-- -----------------------------------------------------
-- Table `sweetnews`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweetnews`.`category` (
  `CategoryId` INT(11) NOT NULL AUTO_INCREMENT,
  `CategoryDescription` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CategoryId`),
  INDEX `cdesc` (`CategoryDescription` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sweetnews`.`source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweetnews`.`source` (
  `SourceId` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(60) NULL DEFAULT NULL,
  `Description` VARCHAR(256) NULL DEFAULT NULL,
  `Url` VARCHAR(2000) NULL DEFAULT NULL,
  `Category` VARCHAR(60) NULL DEFAULT NULL,
  `Language` VARCHAR(45) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `UrlLogo` VARCHAR(2000) NULL DEFAULT NULL,
  `ApprovalStatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`SourceId`),
  INDEX `categorydesc_idx` (`Category` ASC),
  INDEX `desc` (`Description` ASC),
  CONSTRAINT `categorydesc`
    FOREIGN KEY (`Category`)
    REFERENCES `sweetnews`.`category` (`CategoryDescription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sweetnews`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweetnews`.`article` (
  `Author` VARCHAR(65) NOT NULL,
  `Description` VARCHAR(256) NULL DEFAULT NULL,
  `Title` VARCHAR(256) NULL DEFAULT NULL,
  `Url` VARCHAR(2000) NULL DEFAULT NULL,
  `UrlToImage` VARCHAR(2000) NULL DEFAULT NULL,
  `publishTime` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Author`),
  INDEX `artdesc_idx` (`Description` ASC),
  CONSTRAINT `artdesc`
    FOREIGN KEY (`Description`)
    REFERENCES `sweetnews`.`source` (`Description`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sweetnews`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweetnews`.`user` (
  `UserId` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `DOB` DATE NULL DEFAULT NULL,
  `Email` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`UserId`),
  INDEX `email` (`Email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sweetnews`.`user_preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweetnews`.`user_preference` (
  `UserId` INT(11) NOT NULL,
  `CategoryId` INT(11) NULL DEFAULT NULL,
  INDEX `usercat_idx` (`UserId` ASC),
  INDEX `catuser_idx` (`CategoryId` ASC),
  CONSTRAINT `catuser`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `sweetnews`.`category` (`CategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usercat`
    FOREIGN KEY (`UserId`)
    REFERENCES `sweetnews`.`user` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sweetnews`.`userlogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweetnews`.`userlogin` (
  `UserName` VARCHAR(256) NOT NULL,
  `Password` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`UserName`),
  CONSTRAINT `username`
    FOREIGN KEY (`UserName`)
    REFERENCES `sweetnews`.`user` (`Email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
